name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install
        run: npm i
      - name: Cypress Install
        run: npm i cypress @percy/cypress @percy/cli
      - name: Building App
        run: npm run build
      - name: Percy Test
        uses: percy/exec-action@v0.3.1
        with:
          command: npx @percy/cli snapshot build/
        env:
          PERCY_TOKEN: "7f6ed05e6ce8aedfec34f7e6b3d1d9f3dff710f7aaadcc791d0a0421a03c328a"